// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: bfsp.cli.proto

package bfsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_IMAGE   FileType = 0
	FileType_TEXT    FileType = 1
	FileType_UNKNOWN FileType = 2
	FileType_BINARY  FileType = 3
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "IMAGE",
		1: "TEXT",
		2: "UNKNOWN",
		3: "BINARY",
	}
	FileType_value = map[string]int32{
		"IMAGE":   0,
		"TEXT":    1,
		"UNKNOWN": 2,
		"BINARY":  3,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_bfsp_cli_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_bfsp_cli_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_bfsp_cli_proto_rawDescGZIP(), []int{0}
}

type FileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Chunks           map[uint64]string `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FileName         string            `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType         FileType          `protobuf:"varint,4,opt,name=file_type,json=fileType,proto3,enum=bfsp.cli.FileType" json:"file_type,omitempty"`
	FileSize         uint64            `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Directory        []string          `protobuf:"bytes,6,rep,name=directory,proto3" json:"directory,omitempty"`
	CreateTime       int64             `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModificationTime int64             `protobuf:"varint,8,opt,name=modification_time,json=modificationTime,proto3" json:"modification_time,omitempty"`
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bfsp_cli_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_bfsp_cli_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_bfsp_cli_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMetadata) GetChunks() map[uint64]string {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMetadata) GetFileType() FileType {
	if x != nil {
		return x.FileType
	}
	return FileType_IMAGE
}

func (x *FileMetadata) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileMetadata) GetDirectory() []string {
	if x != nil {
		return x.Directory
	}
	return nil
}

func (x *FileMetadata) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FileMetadata) GetModificationTime() int64 {
	if x != nil {
		return x.ModificationTime
	}
	return 0
}

type ViewFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token      string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	FileEncKey string `protobuf:"bytes,3,opt,name=file_enc_key,json=fileEncKey,proto3" json:"file_enc_key,omitempty"`
}

func (x *ViewFileInfo) Reset() {
	*x = ViewFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bfsp_cli_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewFileInfo) ProtoMessage() {}

func (x *ViewFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bfsp_cli_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewFileInfo.ProtoReflect.Descriptor instead.
func (*ViewFileInfo) Descriptor() ([]byte, []int) {
	return file_bfsp_cli_proto_rawDescGZIP(), []int{1}
}

func (x *ViewFileInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ViewFileInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ViewFileInfo) GetFileEncKey() string {
	if x != nil {
		return x.FileEncKey
	}
	return ""
}

var File_bfsp_cli_proto protoreflect.FileDescriptor

var file_bfsp_cli_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x66, 0x73, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x66, 0x73, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x22, 0xec, 0x02, 0x0a, 0x0c, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x06, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x66,
	0x73, 0x70, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x62, 0x66, 0x73, 0x70, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6d, 0x6f,
	0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x39,
	0x0a, 0x0b, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x56, 0x0a, 0x0c, 0x56, 0x69, 0x65,
	0x77, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x20, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x6e, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x63, 0x4b, 0x65,
	0x79, 0x2a, 0x38, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x03, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bfsp_cli_proto_rawDescOnce sync.Once
	file_bfsp_cli_proto_rawDescData = file_bfsp_cli_proto_rawDesc
)

func file_bfsp_cli_proto_rawDescGZIP() []byte {
	file_bfsp_cli_proto_rawDescOnce.Do(func() {
		file_bfsp_cli_proto_rawDescData = protoimpl.X.CompressGZIP(file_bfsp_cli_proto_rawDescData)
	})
	return file_bfsp_cli_proto_rawDescData
}

var file_bfsp_cli_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bfsp_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bfsp_cli_proto_goTypes = []any{
	(FileType)(0),        // 0: bfsp.cli.FileType
	(*FileMetadata)(nil), // 1: bfsp.cli.FileMetadata
	(*ViewFileInfo)(nil), // 2: bfsp.cli.ViewFileInfo
	nil,                  // 3: bfsp.cli.FileMetadata.ChunksEntry
}
var file_bfsp_cli_proto_depIdxs = []int32{
	3, // 0: bfsp.cli.FileMetadata.chunks:type_name -> bfsp.cli.FileMetadata.ChunksEntry
	0, // 1: bfsp.cli.FileMetadata.file_type:type_name -> bfsp.cli.FileType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bfsp_cli_proto_init() }
func file_bfsp_cli_proto_init() {
	if File_bfsp_cli_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bfsp_cli_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FileMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bfsp_cli_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ViewFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bfsp_cli_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bfsp_cli_proto_goTypes,
		DependencyIndexes: file_bfsp_cli_proto_depIdxs,
		EnumInfos:         file_bfsp_cli_proto_enumTypes,
		MessageInfos:      file_bfsp_cli_proto_msgTypes,
	}.Build()
	File_bfsp_cli_proto = out.File
	file_bfsp_cli_proto_rawDesc = nil
	file_bfsp_cli_proto_goTypes = nil
	file_bfsp_cli_proto_depIdxs = nil
}
